import type { Guide } from "./guides";

export const seoGuides: Guide[] = [
  {
    slug: "car-affordability-total-cost",
    category: "Car finance",
    title: "How much car can I afford? Start with the total ownership cost",
    description: "Build a car budget that includes the loan, insurance, tax, fuel, maintenance, registration, and a safety margin.",
    calculatorSlug: "auto-loan",
    keywords: ["how much car can I afford", "car affordability calculator", "total cost of car ownership", "auto loan budget"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["The loan payment is only one part of car cost", "A longer term can hide an expensive purchase", "Stress-test the budget before choosing a vehicle"],
    sections: [
      { heading: "Start with the all-in monthly cost", paragraphs: ["A payment quote does not show what the vehicle will cost to own. Add insurance, fuel or charging, registration, parking, routine servicing, tyres, repairs, and any local tax to the proposed loan payment.", "Use quotes and recent receipts where possible. Insurance can vary sharply by driver and vehicle, while repair risk often rises as a vehicle ages."] },
      { heading: "Separate purchase cash from monthly cash flow", paragraphs: ["List the down payment, taxes, registration, dealer charges, inspection, and immediate maintenance separately. Using every available dollar as a down payment can leave the household exposed to the first repair or insurance bill.", "If a trade-in has finance outstanding, compare its settlement amount with its market value. Rolling negative equity into a new loan increases the new balance without improving the new vehicle."], checklist: ["Down payment and trade-in equity", "Taxes and registration", "Insurance quote", "Fuel, maintenance, parking, and repairs"] },
      { heading: "Compare amount, rate, and term together", paragraphs: ["A longer loan term generally reduces the required payment but can increase total interest and keep the balance above the vehicle's value for longer. Compare the same vehicle price across several realistic terms.", "Use the auto-loan calculator to view payment and total interest, then add the non-loan costs. Do not treat lender approval as proof that the total ownership budget is comfortable."] },
      { heading: "Set a limit that survives a weak month", paragraphs: ["Test the all-in cost against take-home income after essential bills, minimum debt payments, and savings. For variable or commission income, use a weaker month rather than the best recent month.", "Leave room for price changes and repairs. The right limit is the one that preserves essential spending and emergency savings, not the maximum amount a seller can arrange."] },
    ],
    sources: [{ label: "CFPB — auto loans", url: "https://www.consumerfinance.gov/consumer-tools/auto-loans/" }, { label: "FTC — financing or leasing a car", url: "https://consumer.ftc.gov/articles/financing-or-leasing-car" }],
  },
  {
    slug: "credit-card-minimum-payment-trap",
    category: "Credit cards",
    title: "Credit card minimum payments: why payoff can take so long",
    description: "Understand minimum-payment math, compare a fixed extra payment, and build a safer credit-card payoff plan.",
    calculatorSlug: "credit-card-payoff",
    keywords: ["credit card payoff calculator", "minimum payment payoff time", "how long to pay off credit card", "credit card interest"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["Minimum payments are designed to keep the account current, not to clear it quickly", "New spending can erase payoff progress", "A fixed extra payment can materially reduce time and interest"],
    sections: [
      { heading: "What a minimum payment actually does", paragraphs: ["A minimum payment usually covers current interest and a portion of principal, subject to the issuer's formula and local rules. As the balance falls, a percentage-based minimum may also fall, which can extend payoff time.", "Read the statement for the actual minimum-payment formula, APR, fees, due date, and any payoff illustration. The contract and statement govern the account, not a generic calculator."] },
      { heading: "Model a no-new-spending baseline", paragraphs: ["First calculate payoff assuming no new purchases, cash advances, balance transfers, or missed payments. This isolates the existing balance and shows how the payment level changes time and interest.", "Then compare the required minimum with a fixed monthly payment you can repeat. Keep every required payment current before directing extra money to one target card."], checklist: ["Current balance", "Purchase APR and other APRs", "Required minimum", "A repeatable fixed payment"] },
      { heading: "Protect the plan from common resets", paragraphs: ["Continuing to spend on the card can keep the balance flat even while payments are made. Move ordinary spending to a controlled cash-flow plan where practical and avoid using one card to pay another debt.", "Keep a small emergency buffer so one surprise does not immediately recreate the balance. Automating at least the minimum helps reduce late-payment risk."] },
      { heading: "Get help before the account becomes unmanageable", paragraphs: ["If minimums are already unaffordable, contact the issuer early and ask about hardship options. A reputable nonprofit or regulated debt adviser may help evaluate the full situation.", "Be cautious with companies promising guaranteed debt elimination or asking for large upfront fees. Compare any consolidation offer by total cost, term, fees, and the risk of converting unsecured debt into secured debt."] },
    ],
    sources: [{ label: "CFPB — credit cards", url: "https://www.consumerfinance.gov/consumer-tools/credit-cards/" }, { label: "MoneyHelper — reducing card debt", url: "https://www.moneyhelper.org.uk/en/everyday-money/credit/how-to-reduce-the-cost-of-your-credit-and-store-card-debt" }],
  },
  {
    slug: "debt-to-income-mortgage-readiness",
    category: "Home buying",
    title: "Debt-to-income ratio for a mortgage: calculate it before you apply",
    description: "Calculate monthly debt against gross income, understand what the ratio misses, and prepare a resilient mortgage budget.",
    calculatorSlug: "debt-to-income",
    keywords: ["debt to income ratio mortgage", "DTI calculator", "calculate debt to income", "mortgage readiness"],
    readTime: "7 min",
    reviewed: "August 9, 2026",
    takeaways: ["DTI compares monthly debt obligations with gross monthly income", "Lender rules vary by product and jurisdiction", "Approval and personal affordability are different tests"],
    sections: [
      { heading: "Calculate the ratio consistently", paragraphs: ["Debt-to-income ratio divides qualifying monthly debt obligations by gross monthly income and expresses the result as a percentage. Use the income and obligation definitions required by the relevant lender or program.", "Typical debt inputs can include housing payments, vehicle and student loans, required card payments, and other contractual obligations. Ordinary living costs may not appear in DTI even though they matter to affordability."] },
      { heading: "Build the inputs from documents", paragraphs: ["Use recent statements and credit reports where available rather than estimates. For irregular income, lenders may use documented history and their own averaging rules.", "Do not remove a debt from your personal budget simply because a particular calculation excludes it. Childcare, insurance, transport, utilities, and healthcare can determine whether the payment works in real life."], checklist: ["Gross monthly income used by the lender", "Proposed housing payment", "Required monthly debt payments", "Essential costs outside the formal ratio"] },
      { heading: "Improve resilience, not just the percentage", paragraphs: ["Reducing revolving balances can lower required payments and interest exposure. Avoid opening new debt immediately before an application unless there is a compelling reason.", "A larger emergency reserve or smaller purchase can improve the plan even if it does not change the lender's headline ratio. Focus on the complete household cash flow."] },
      { heading: "Treat thresholds as product-specific", paragraphs: ["There is no universal approval threshold. Limits and exceptions depend on country, lender, loan type, credit profile, down payment, reserves, and other underwriting factors.", "Use Numora to understand the scenario, then obtain the current criteria and regulated disclosures from the lender. Never shape inputs to misrepresent an application."] },
    ],
    sources: [{ label: "CFPB — what is a debt-to-income ratio?", url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-debt-to-income-ratio-en-1791/" }, { label: "Fannie Mae — calculating DTI", url: "https://yourhome.fanniemae.com/buy/calculating-your-debt-to-income-ratio" }],
  },
  {
    slug: "refinance-break-even-closing-costs",
    category: "Mortgages",
    title: "Mortgage refinance break-even: when closing costs erase the saving",
    description: "Compare refinance closing costs with monthly savings, term changes, total interest, and the time you expect to keep the loan.",
    calculatorSlug: "refinance-break-even",
    keywords: ["refinance break even calculator", "mortgage refinance closing costs", "when should I refinance", "refinance savings"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["A lower payment does not automatically mean a cheaper loan", "Simple break-even is closing costs divided by monthly saving", "Term resets and financed fees require a total-cost comparison"],
    sections: [
      { heading: "Define the real monthly saving", paragraphs: ["Compare principal and interest on the current loan with the proposed refinance using consistent assumptions. Separate changes in taxes, insurance, or escrow because they may not be savings created by the new loan.", "If fees are added to the new balance, the payment can look attractive while the borrower pays interest on those costs. Record both cash-paid and financed charges."] },
      { heading: "Calculate more than one break-even point", paragraphs: ["A simple break-even estimate divides eligible upfront costs by the monthly payment saving. It answers how long the payment difference takes to recover the closing cost, but it does not capture every consequence.", "Also compare remaining total interest, the new maturity date, the balance after several likely move dates, and any early-repayment charge on the current loan."], checklist: ["All lender and third-party closing costs", "Monthly principal-and-interest difference", "Old and new payoff dates", "Expected time in the property"] },
      { heading: "Watch for a term reset", paragraphs: ["Replacing a loan with a fresh long term can reduce the monthly payment because principal is spread over more payments. Total interest may rise even when the rate falls.", "Compare the new loan using a term close to the remaining term as well as the lender's standard offer. If cash flow is the priority, make the longer-term trade-off explicit."] },
      { heading: "Use current written offers", paragraphs: ["Rates and costs change. Compare official estimates issued on similar dates and check whether points, credits, or adjustable-rate features differ.", "A calculator is a screening tool. Review the final disclosures and seek qualified advice for tax, legal, or regulated questions in your jurisdiction."] },
    ],
    sources: [{ label: "CFPB — mortgages", url: "https://www.consumerfinance.gov/consumer-tools/mortgages/" }, { label: "CFPB — explore mortgage rates and costs", url: "https://www.consumerfinance.gov/owning-a-home/explore-rates/" }],
  },
  {
    slug: "50-30-20-budget-examples",
    category: "Budgeting",
    title: "50/30/20 budget examples: adapt the rule to your real income",
    description: "Apply the 50/30/20 framework to take-home pay, classify difficult expenses, and adjust it for housing, debt, and savings priorities.",
    calculatorSlug: "budget-50-30-20",
    keywords: ["50 30 20 budget examples", "50/30/20 calculator", "budget percentages", "take home pay budget"],
    readTime: "7 min",
    reviewed: "August 9, 2026",
    takeaways: ["Use take-home income consistently", "The categories are planning guides, not moral judgments", "A temporary custom split can be more useful than forcing the rule"],
    sections: [
      { heading: "Start with the money available to spend", paragraphs: ["Use a consistent after-tax income figure and account for payroll deductions that already fund benefits or retirement. Mixing gross and take-home figures makes the percentages misleading.", "For variable income, build the baseline around a conservative month and decide in advance how stronger months will be divided."] },
      { heading: "Classify needs, wants, and future goals", paragraphs: ["Needs generally include essential housing, basic food, utilities, required transport, insurance, healthcare, and minimum debt payments. Wants are expenses that can be reduced or delayed without immediate harm.", "Savings and extra debt payments improve the future balance sheet. Classification can be ambiguous: a basic phone may be essential while a premium upgrade is partly discretionary."], checklist: ["Essential commitments", "Flexible lifestyle spending", "Emergency and long-term saving", "Debt payments above the minimum"] },
      { heading: "Work through a practical example", paragraphs: ["With 3,000 of take-home income, the reference split would allocate 1,500 to needs, 900 to wants, and 600 to savings or extra debt repayment. The currency does not change the percentage logic.", "If essential housing and childcare already exceed the reference need share, do not hide the gap. Reduce flexible costs where realistic, review major contracts, or use a temporary split that reflects the current constraint."] },
      { heading: "Change the framework when the goal changes", paragraphs: ["Someone clearing high-cost debt may direct more than the reference savings share toward repayment. A household rebuilding after an emergency may temporarily reduce wants to restore cash reserves.", "Review the plan monthly at first. The objective is a repeatable cash-flow system, not perfect adherence to three numbers."] },
    ],
    sources: [{ label: "CFPB — consumer financial tools", url: "https://www.consumerfinance.gov/consumer-tools/" }, { label: "ASIC Moneysmart — budget planner", url: "https://moneysmart.gov.au/budgeting/budget-planner" }],
  },
  {
    slug: "net-worth-tracking-guide",
    category: "Financial planning",
    title: "How to calculate net worth without misleading yourself",
    description: "Create a consistent asset-and-debt snapshot, value uncertain items conservatively, and track financial direction over time.",
    calculatorSlug: "net-worth",
    keywords: ["how to calculate net worth", "net worth calculator", "assets minus liabilities", "track net worth"],
    readTime: "7 min",
    reviewed: "August 9, 2026",
    takeaways: ["Net worth equals assets minus liabilities", "Use realistic values and consistent dates", "The trend is often more useful than one headline number"],
    sections: [
      { heading: "Choose a clear snapshot date", paragraphs: ["Gather account balances and reasonable asset values for the same date or a narrow date range. Mixing a recent debt balance with an old, optimistic asset value can distort the result.", "List ownership carefully for joint accounts and shared debts. The purpose is a useful personal planning view, not a formal valuation for tax, court, or lending purposes."] },
      { heading: "Value assets conservatively", paragraphs: ["Cash and quoted investments usually have observable balances. Property, vehicles, private businesses, collectibles, and restricted accounts may require estimates and selling costs.", "Record the method used and avoid updating uncertain assets only when prices rise. Consistency matters more than precision that cannot be supported."], checklist: ["Cash and deposit accounts", "Investments and retirement accounts", "Property and other saleable assets", "Loans, cards, tax, and other obligations"] },
      { heading: "Keep liquidity visible", paragraphs: ["A positive net worth does not guarantee enough accessible cash. A household can own valuable property while struggling to meet a near-term bill.", "Track liquid savings, high-cost debt, and retirement assets as separate supporting measures. That prevents one total from hiding cash-flow risk."] },
      { heading: "Review the trend on a useful schedule", paragraphs: ["Monthly or quarterly review is usually enough for planning. Daily market moves can add noise without changing the actions available.", "Look for the cause of change: saving, debt reduction, investment movement, asset revaluation, or a new obligation. Protect statements and identifiers; Numora's calculator does not require an account or store the values entered."] },
    ],
    sources: [{ label: "SEC Investor.gov — roadmap to saving and investing", url: "https://www.investor.gov/introduction-investing/getting-started/roadmap-saving-and-investing" }, { label: "FCAC — savings and investments", url: "https://www.canada.ca/en/financial-consumer-agency/services/savings-investments.html" }],
  },
  {
    slug: "rent-affordability-complete-budget",
    category: "Renting",
    title: "How much rent can I afford? Build the complete monthly budget",
    description: "Estimate affordable rent after utilities, deposits, transport, debt, irregular income, and the emergency costs of moving.",
    calculatorSlug: "rent-affordability",
    keywords: ["how much rent can I afford", "rent affordability calculator", "rent budget", "income needed for rent"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["A rent-to-income percentage is only a starting point", "Utilities and transport can change the best location", "Upfront moving cash needs its own plan"],
    sections: [
      { heading: "Start after unavoidable obligations", paragraphs: ["Compare proposed rent with take-home income after minimum debt payments, essential healthcare, childcare, transport, food, and insurance. A gross-income percentage can miss major differences between households.", "Use a conservative income figure when hours, commissions, or freelance work vary. The budget should survive a weaker month without immediately creating debt."] },
      { heading: "Price the home and the location together", paragraphs: ["Add utilities, internet, parking, renter insurance, service charges, and likely annual increases. A cheaper property can cost more overall if it creates a large transport or energy bill.", "Confirm which services are included and how variable costs have behaved. Ask for the current lease terms and required disclosures in your jurisdiction."], checklist: ["Rent and recurring charges", "Utilities and communications", "Transport and parking", "Insurance and essential local costs"] },
      { heading: "Prepare the upfront cash", paragraphs: ["Deposits, advance rent, application or referencing costs where lawful, moving, basic furniture, and utility setup may fall close together. Keep these separate from the monthly affordability calculation.", "Understand how the deposit must be protected and the conditions for deductions. Photograph the property's condition and retain the inventory and correspondence."] },
      { heading: "Stress-test before signing", paragraphs: ["Test a rent increase, a utility spike, and a temporary income drop. If the plan fails immediately, reduce the target or build a larger reserve before moving.", "Read the full lease, including notice, renewal, guest, maintenance, and early-exit terms. Rules vary, so use official local housing guidance for legal questions."] },
    ],
    sources: [{ label: "HUD — rental assistance and housing", url: "https://www.hud.gov/renting" }, { label: "MoneyHelper — renting", url: "https://www.moneyhelper.org.uk/en/homes/renting" }],
  },
  {
    slug: "student-loan-repayment-plan",
    category: "Student loans",
    title: "How to build a student-loan repayment plan before paying extra",
    description: "Inventory each loan, compare required and accelerated payments, and check official repayment or relief options first.",
    calculatorSlug: "student-loan",
    keywords: ["student loan repayment calculator", "pay off student loans faster", "student loan payment plan", "student loan interest"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["Separate loans by balance, rate, type, and protections", "Official repayment options can matter more than a generic payoff calculation", "Keep a cash buffer before making irreversible extra payments"],
    sections: [
      { heading: "Create a loan-by-loan inventory", paragraphs: ["Record the lender or servicer, current balance, interest rate, whether the rate can change, required payment, remaining term, and the loan's legal type. Do not assume every education loan has the same protections.", "Check statements and the official account record. Resolve missing or disputed information before building an aggressive repayment schedule."] },
      { heading: "Model the contractual path first", paragraphs: ["Calculate the payment and total interest under the current terms, then compare a repeatable extra payment. Specify how the servicer applies extra money and whether it advances the due date or reduces principal.", "If rates differ, directing extra money to the highest-rate loan generally reduces interest fastest, provided every required payment remains current."], checklist: ["Balance and rate for each loan", "Required payment and payoff date", "Repayment-plan eligibility", "Instructions for applying extra payments"] },
      { heading: "Check official options before refinancing", paragraphs: ["Income-driven, deferment, forgiveness, hardship, tax, and subsidy rules are jurisdiction- and program-specific. Use the official government source and confirm eligibility before changing the loan.", "Refinancing a government-backed loan into a private product can permanently remove protections. Compare the lost options as well as the rate and payment."] },
      { heading: "Balance payoff with financial resilience", paragraphs: ["Maintain essential expenses and a basic emergency buffer. An irreversible extra payment cannot cover next month's rent or medical bill.", "Review the plan after income changes or policy updates. Numora provides educational scenarios, not a determination of program eligibility."] },
    ],
    sources: [{ label: "Federal Student Aid — Loan Simulator", url: "https://studentaid.gov/loan-simulator/" }, { label: "CFPB — student loans", url: "https://www.consumerfinance.gov/consumer-tools/student-loans/" }],
  },
  {
    slug: "business-loan-affordability-cash-flow",
    category: "Business finance",
    title: "Can the business afford a loan? Test cash flow before borrowing",
    description: "Compare loan payments with conservative operating cash flow, working-capital needs, collateral risk, fees, and a weak-sales scenario.",
    calculatorSlug: "business-loan",
    keywords: ["business loan calculator", "can my business afford a loan", "business loan payment", "small business cash flow"],
    readTime: "9 min",
    reviewed: "August 9, 2026",
    takeaways: ["Revenue is not cash available for debt service", "Test weak sales and slower collections", "Personal guarantees and collateral change the risk"],
    sections: [
      { heading: "Start with cash available for repayment", paragraphs: ["Build a monthly cash-flow view from cash receipts less operating costs, tax reserves, owner compensation, equipment needs, and working-capital changes. Accounting profit and bank cash are not interchangeable.", "Seasonal businesses should model the weakest period and the timing gap between paying suppliers and collecting customers."] },
      { heading: "Calculate the complete debt service", paragraphs: ["Use the stated amount, rate, term, payment frequency, and every required fee. Include existing business debt and avoid counting the same expected growth twice.", "A loan intended to generate revenue should still have a repayment plan if sales arrive later or below forecast."], checklist: ["Loan proceeds actually received", "Payment schedule and total repayable", "Existing debt and leases", "Working-capital reserve after funding"] },
      { heading: "Stress-test the operating assumptions", paragraphs: ["Reduce sales, delay collections, increase a major input cost, and test a rate change where relevant. The objective is to identify which event breaks repayment first.", "Document a response for each weak scenario, such as delaying discretionary spending or reducing the amount borrowed. Do not rely on emergency borrowing as the only backup."] },
      { heading: "Read the security and guarantee terms", paragraphs: ["Understand collateral, personal guarantees, covenants, reporting duties, prepayment rules, default triggers, and lender enforcement rights. These can matter more than a small rate difference.", "Use regulated or government-backed business guidance and obtain professional legal, accounting, or tax advice where the commitment is material."] },
    ],
    sources: [{ label: "US Small Business Administration — loans", url: "https://www.sba.gov/funding-programs/loans" }, { label: "British Business Bank — finance options", url: "https://www.british-business-bank.co.uk/finance-options" }],
  },
  {
    slug: "cagr-vs-average-return",
    category: "Investing",
    title: "CAGR vs average return: which growth rate describes your investment?",
    description: "Understand compound annual growth rate, why simple averages can mislead, and when cash flows require a different return measure.",
    calculatorSlug: "cagr",
    keywords: ["CAGR calculator", "CAGR vs average return", "compound annual growth rate", "annualized return"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["CAGR connects a beginning value with an ending value over time", "A simple arithmetic average does not capture volatility drag", "Deposits and withdrawals require a cash-flow-aware analysis"],
    sections: [
      { heading: "What CAGR answers", paragraphs: ["Compound annual growth rate is the constant annual rate that would transform a beginning value into an ending value over a stated number of years. It smooths the path into one comparable annualized number.", "The formula is ending value divided by beginning value, raised to one divided by years, minus one. It requires positive beginning and ending values for the standard interpretation."] },
      { heading: "Why the simple average can be wrong", paragraphs: ["A gain of 50% followed by a loss of 50% has an arithmetic average of zero, but the ending value is below the start. Returns compound from a changing base.", "CAGR captures the start-to-finish effect but hides the volatility experienced along the way. Two investments can have the same CAGR and very different risk."], checklist: ["Exact start and end dates", "Beginning and ending values", "Fees and distributions", "Volatility and drawdowns outside the CAGR"] },
      { heading: "Handle cash flows separately", paragraphs: ["Contributions and withdrawals can make a portfolio CAGR look better or worse even when investment performance is unchanged. Money-weighted and time-weighted return methods answer different questions.", "Use a performance statement or qualified calculation when cash flows are material. Do not treat a deposit as investment gain."] },
      { heading: "Compare like with like", paragraphs: ["Use the same period, currency, fee treatment, dividend treatment, and inflation basis. A nominal pre-fee CAGR is not directly comparable with a real after-fee return.", "Past performance is not a forecast. Use CAGR to describe history or a scenario, not to promise a future result."] },
    ],
    sources: [{ label: "SEC Investor.gov — compound interest calculator", url: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" }, { label: "SEC Investor.gov — average annual total return", url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/average-annual-total-return" }],
  },
  {
    slug: "dividend-yield-vs-total-return",
    category: "Investing",
    title: "Dividend yield vs total return: do not judge a stock by yield alone",
    description: "Calculate dividend yield, include price changes and reinvestment, and identify the risks hidden behind an unusually high percentage.",
    calculatorSlug: "dividend-yield",
    keywords: ["dividend yield calculator", "dividend yield vs total return", "calculate dividend income", "high dividend yield risk"],
    readTime: "8 min",
    reviewed: "August 9, 2026",
    takeaways: ["Dividend yield is annual dividends divided by market price", "A falling share price can mechanically raise yield", "Total return includes income and price movement"],
    sections: [
      { heading: "Calculate the yield with consistent inputs", paragraphs: ["Dividend yield generally divides annual dividends per share by the current share price. Confirm whether the annual dividend is trailing, declared, or estimated.", "Special distributions and foreign-exchange effects can distort the number. Use the same basis when comparing securities."] },
      { heading: "Understand why a high yield can be a warning", paragraphs: ["Yield rises when the dividend increases or the share price falls. A very high figure can therefore reflect market concern about earnings, debt, cash flow, or the sustainability of the distribution.", "Dividends are not guaranteed. A company may reduce, suspend, or change them, and the share price can fall by more than the income received."], checklist: ["Dividend history and policy", "Cash flow and debt obligations", "Payout sustainability", "Price and sector concentration risk"] },
      { heading: "Move from yield to total return", paragraphs: ["Total return includes distributions plus the change in market value, with a clear assumption about reinvestment. That broader measure is more useful for comparing wealth outcomes.", "Fees, withholding tax, personal tax, and currency conversion can reduce what the investor keeps. Treatment varies by account and jurisdiction."] },
      { heading: "Use yield inside a diversified plan", paragraphs: ["Do not select a concentrated portfolio solely to reach an income target. Consider diversification, liquidity, business quality, valuation, and the possibility that income changes.", "Use regulated disclosures and official filings. Numora's calculator illustrates a scenario and does not recommend a security."] },
    ],
    sources: [{ label: "SEC Investor.gov — stocks", url: "https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks" }, { label: "FINRA — stocks", url: "https://www.finra.org/investors/investing/investment-products/stocks" }],
  },
  {
    slug: "fire-number-assumptions",
    category: "Financial independence",
    title: "Your FIRE number is a scenario, not a promise: test the assumptions",
    description: "Build a financial-independence target from spending, inflation, fees, tax, withdrawal assumptions, and a margin for an uncertain future.",
    calculatorSlug: "fire-number",
    keywords: ["FIRE number calculator", "financial independence number", "how much money to retire early", "FIRE assumptions"],
    readTime: "9 min",
    reviewed: "August 9, 2026",
    takeaways: ["Start from sustainable annual spending", "A withdrawal multiple is an assumption, not a guarantee", "Long retirements need stress tests for bad early returns"],
    sections: [
      { heading: "Build a realistic spending base", paragraphs: ["Start with current spending, then adjust for costs that may disappear or arrive in financial independence. Housing, healthcare, dependants, tax, insurance, travel, and major replacements deserve separate attention.", "Use today's purchasing power consistently. If the portfolio projection is nominal, inflate the future spending target on the same basis."] },
      { heading: "Translate spending into a portfolio scenario", paragraphs: ["A common planning approach divides annual portfolio-funded spending by an assumed withdrawal rate, which is equivalent to multiplying spending by a chosen factor. The result changes materially with the assumption.", "No factor guarantees success. Retirement length, asset allocation, fees, tax, inflation, and spending flexibility all influence sustainability."], checklist: ["Annual spending funded by the portfolio", "Reliable income outside the portfolio", "Fees and tax", "Withdrawal-rate range rather than one number"] },
      { heading: "Test sequence and longevity risk", paragraphs: ["Poor market returns early in withdrawals can damage a portfolio more than the same average returns arriving later. Run a weaker-return scenario and a longer-than-expected retirement.", "Flexible spending, part-time income, a cash reserve, or a later start can improve resilience, but each has trade-offs."] },
      { heading: "Use milestones instead of one distant finish line", paragraphs: ["Track savings rate, emergency reserves, high-cost debt, invested assets, and the portion of spending already covered by reliable income. These milestones show progress before the final target is reached.", "Review annually and after major life changes. For pension, tax, insurance, or regulated advice, use a qualified professional in the relevant country."] },
    ],
    sources: [{ label: "SEC Investor.gov — retirement toolkit", url: "https://www.investor.gov/additional-resources/retirement-toolkit" }, { label: "US Department of Labor — preparing for retirement", url: "https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/resource-center/publications/top-10-ways-to-prepare-for-retirement" }],
  },
];
